# frozen_string_literal: true

require "rails/generators/base"
require "json"

module Rails
  module Generators
    class FromIrGenerator < Base # :nodoc:
      source_root File.expand_path("templates", __dir__)

      argument :ir_path, type: :string, banner: "PATH_TO_IR_JSON"

      READONLY_ATTRIBUTES = %w[id created_at updated_at].freeze
      RESERVED_NAMES = %w[
        Module Class Object Kernel Method Process Signal Thread Fiber
        BasicObject Integer Float String Array Hash Set Struct Data
        Application Base Engine Railtie Record
      ].freeze

      def validate_file
        unless File.exist?(ir_path)
          say_status "error", "File not found: #{ir_path}", :red
          raise SystemExit
        end
      end

      def parse_and_validate
        content = File.read(ir_path)
        @ir_data = JSON.parse(content)

        unless @ir_data.is_a?(Hash) && @ir_data["$schema"]&.start_with?("ddd-ir/")
          say_status "error", "Invalid IR file: missing '$schema' field", :red
          raise SystemExit
        end

        unless @ir_data["resources"].is_a?(Array) && @ir_data["resources"].any?
          say_status "error", "Invalid IR file: missing or empty 'resources' array", :red
          raise SystemExit
        end

        say_status "found", "#{@ir_data['resources'].size} resources in #{ir_path}", :green
      rescue JSON::ParserError => e
        say_status "error", "Invalid JSON: #{e.message}", :red
        raise SystemExit
      end

      def generate_resources
        sorted = topological_sort(@ir_data["resources"])

        sorted.each do |resource|
          name = resource["name"]

          if RESERVED_NAMES.include?(name)
            say_status "error", "Resource name '#{name}' conflicts with Ruby/Rails constant. Rename in ir.json (e.g., 'Course#{name}' instead of '#{name}').", :red
            raise SystemExit
          end

          attrs = build_attribute_args(resource)

          say_status "scaffold", "#{name} #{attrs.join(' ')}", :cyan

          generate "scaffold", name, *attrs,
            "--no-test-framework",
            "--no-resource-route",
            "--skip-collision-check"

          patch_custom_fks(resource)
          patch_optional_fks(resource)
          patch_endpoint_collection(resource)
          patch_entity_defaults(resource)
          patch_entity_transitions(resource)
          patch_unique_indexes(resource)
          patch_endpoint_actions(resource)
        end

        add_has_many_to_parents(sorted)
      end

      def generate_routes
        sorted = topological_sort(@ir_data["resources"])
        lines = ["# Auto-generated by rails g from_ir", "# Add to config/routes.rb: load Rails.root.join('config/routes_ddd.rb')", ""]

        sorted.each do |resource|
          plural = resource["plural"] || resource["name"].underscore.pluralize
          endpoint_name = "#{plural.camelize}Endpoint"

          if resource["parent"]
            parent_plural = resource["parent"].underscore.pluralize
            lines << "scope \"/#{parent_plural}/:#{resource['parent'].underscore}_id\" do"
            lines << "  endpoint #{endpoint_name}"
            lines << "end"
          else
            lines << "endpoint #{endpoint_name}"
          end
        end

        path = File.join(destination_root, "config/routes_ddd.rb")
        File.write(path, lines.join("\n") + "\n")
        say_status "routes", "config/routes_ddd.rb", :green
      end

      def print_summary
        names = @ir_data["resources"].map { |r| r["name"] }
        say ""
        say "Generated #{names.size} DDD resources: #{names.join(', ')}"
        say ""
        say "Next steps:"
        say "  1. Run migrations:  rails db:migrate"
        say "  2. Add routes to config/routes.rb:"
        @ir_data["resources"].each do |r|
          if r["parent"]
            say "       # #{r['name']} is nested under #{r['parent']}"
          else
            say "       endpoint #{r['plural']&.camelize || r['name'].pluralize}Endpoint"
          end
        end
        say "  3. Start server:    rails server"
      end

      private

      def build_attribute_args(resource)
        attrs = []

        (resource["relations"] || {}).each do |name, rel|
          attrs << "#{name}:references" if rel["kind"] == "belongs_to"
        end

        (resource["attributes"] || {}).each do |name, info|
          next if READONLY_ATTRIBUTES.include?(name)
          next if name.end_with?("_id")

          type = info["type"] || "string"
          attrs << "#{name}:#{type}"
        end

        attrs
      end

      def patch_custom_fks(resource)
        custom_fks = (resource["relations"] || {}).select do |assoc_name, rel|
          rel["kind"] == "belongs_to" && assoc_name != rel["resource"].downcase
        end

        return if custom_fks.empty?

        name = resource["name"]
        file_name = name.underscore

        custom_fks.each do |assoc_name, rel|
          target = rel["resource"]
          wrong_record = "#{assoc_name.camelize}Record"
          right_record = "#{target}Record"
          target_table = target.downcase.pluralize
          required = rel["required"] != false

          say_status "patch", "#{name}: #{assoc_name} → #{target}", :yellow

          patch_record(file_name, assoc_name, wrong_record, right_record, required)
          patch_migration(file_name, name, assoc_name, target_table, required)
          patch_endpoint(file_name, name, assoc_name, target)
        end
      end

      def patch_record(file_name, assoc_name, wrong_record, right_record, required)
        path = File.join(destination_root, "app/records/#{file_name}_record.rb")
        return unless File.exist?(path)

        content = File.read(path)
        old_line = "belongs_to :#{assoc_name}, class_name: \"#{wrong_record}\""

        if required
          new_line = "belongs_to :#{assoc_name}, class_name: \"#{right_record}\", foreign_key: \"#{assoc_name}_id\""
        else
          new_line = "belongs_to :#{assoc_name}, class_name: \"#{right_record}\", foreign_key: \"#{assoc_name}_id\", optional: true"
        end

        File.write(path, content.gsub(old_line, new_line))
      end

      def patch_migration(file_name, name, assoc_name, target_table, required)
        migration = Dir.glob(File.join(destination_root, "db/migrate/*_create_#{file_name.pluralize}.rb")).first
        return unless migration && File.exist?(migration)

        content = File.read(migration)
        old_ref = "t.references :#{assoc_name}, null: false, foreign_key: true"
        new_ref = if required
          "t.references :#{assoc_name}, null: false, foreign_key: { to_table: :#{target_table} }"
        else
          "t.references :#{assoc_name}, foreign_key: { to_table: :#{target_table} }"
        end

        File.write(migration, content.gsub(old_ref, new_ref))
      end

      def patch_endpoint(file_name, name, assoc_name, target)
        path = File.join(destination_root, "app/endpoints/#{file_name.pluralize}_endpoint.rb")
        return unless File.exist?(path)

        content = File.read(path)
        old_rel = "#{assoc_name}: { kind: :belongs_to, resource: \"#{assoc_name.camelize}\" }"
        new_rel = "#{assoc_name}: { kind: :belongs_to, resource: \"#{target}\" }"

        File.write(path, content.gsub(old_rel, new_rel))
      end

      def patch_optional_fks(resource)
        (resource["relations"] || {}).each do |assoc_name, rel|
          next unless rel["kind"] == "belongs_to" && rel["required"] == false

          name = resource["name"]
          file_name = name.underscore

          record_path = File.join(destination_root, "app/records/#{file_name}_record.rb")
          if File.exist?(record_path)
            content = File.read(record_path)
            content.gsub!(/belongs_to :#{assoc_name}(.*)$/) do
              line = "belongs_to :#{assoc_name}#{$1}"
              line.include?("optional:") ? line : line.rstrip + ", optional: true"
            end
            File.write(record_path, content)
          end

          migration = Dir.glob(File.join(destination_root, "db/migrate/*_create_#{file_name.pluralize}.rb")).first
          if migration && File.exist?(migration)
            content = File.read(migration)
            content.gsub!(/t\.references :#{assoc_name}, null: false,/, "t.references :#{assoc_name},")
            File.write(migration, content)
          end
        end
      end

      def patch_endpoint_collection(resource)
        coll = resource["collection"]
        return unless coll && coll.any?

        file_name = resource["name"].underscore
        plural = resource["plural"] || file_name.pluralize
        path = File.join(destination_root, "app/endpoints/#{plural}_endpoint.rb")
        return unless File.exist?(path)

        content = File.read(path)

        if coll["filter"]
          old_filter = content[/filter: \[.*?\]/]
          new_filter = "filter: [#{coll['filter'].map { |f| ":#{f}" }.join(', ')}]"
          content.gsub!(old_filter, new_filter) if old_filter
        end

        if coll["search"]
          if content.include?("per_page:")
            content.gsub!(/per_page: (\d+)/) { "search: [#{coll['search'].map { |s| ":#{s}" }.join(', ')}],\n    per_page: #{$1}" }
          end
        end

        if coll["sort"]
          old_sort = content[/sort: \[.*?\]/]
          new_sort = "sort: [#{coll['sort'].map { |s| ":#{s}" }.join(', ')}]"
          content.gsub!(old_sort, new_sort) if old_sort
        end

        if coll["per_page"]
          content.gsub!(/per_page: \d+/, "per_page: #{coll['per_page']}")
        end

        File.write(path, content)
      end

      def add_has_many_to_parents(resources)
        resources.each do |resource|
          (resource["relations"] || {}).each do |assoc_name, rel|
            next unless rel["kind"] == "belongs_to"

            target = rel["resource"]
            child_name = resource["name"]
            child_plural = resource["plural"] || child_name.underscore.pluralize
            child_record = "#{child_name}Record"
            fk = "#{assoc_name}_id"

            parent_file = File.join(destination_root, "app/records/#{target.underscore}_record.rb")
            next unless File.exist?(parent_file)

            content = File.read(parent_file)
            has_many_line = "  has_many :#{child_plural}, class_name: \"#{child_record}\", foreign_key: \"#{fk}\""
            next if content.include?(":#{child_plural}")

            content.sub!(/^end\s*\z/, "#{has_many_line}\nend\n")
            File.write(parent_file, content)
            say_status "has_many", "#{target}Record → #{child_plural}", :yellow
          end
        end
      end

      def patch_entity_defaults(resource)
        defaults = {}
        (resource["attributes"] || {}).each do |attr_name, info|
          next unless info.key?("default")
          defaults[attr_name] = info["default"]
        end
        return if defaults.empty?

        file_name = resource["name"].underscore
        path = File.join(destination_root, "app/entities/#{file_name}.rb")
        return unless File.exist?(path)

        content = File.read(path)
        defaults.each do |attr_name, default_val|
          ruby_val = case default_val
            when String then default_val.inspect
            when NilClass then "nil"
            else default_val.to_s
          end
          content.gsub!(
            /attribute :#{attr_name}, (:\w+)(?!.*default:)$/,
            "attribute :#{attr_name}, \\1, default: #{ruby_val}"
          )
        end
        File.write(path, content)
        say_status "defaults", "#{resource['name']}: #{defaults.keys.join(', ')}", :yellow
      end

      def patch_entity_transitions(resource)
        t = resource["transitions"]
        return unless t && t["events"]&.any?

        file_name = resource["name"].underscore
        path = File.join(destination_root, "app/entities/#{file_name}.rb")
        return unless File.exist?(path)

        content = File.read(path)
        return if content.include?("transitions :#{t['field']}")

        lines = [""]
        lines << "  transitions :#{t['field']},"
        events = t["events"].map do |event_name, cfg|
          from = cfg["from"]
          from_ruby = from.is_a?(Array) ? "[#{from.map { |f| "\"#{f}\"" }.join(', ')}]" : "\"#{from}\""
          "    #{event_name}: { from: #{from_ruby}, to: \"#{cfg['to']}\" }"
        end
        lines << events.join(",\n")

        content.sub!(/^end\s*\z/, "#{lines.join("\n")}\nend\n")
        File.write(path, content)
        say_status "transitions", "#{resource['name']}: #{t['events'].keys.join(', ')}", :yellow
      end

      def patch_unique_indexes(resource)
        uniques = resource["unique"]
        return unless uniques&.any?

        file_name = resource["name"].underscore
        table_name = resource["plural"] || file_name.pluralize
        migration = Dir.glob(File.join(destination_root, "db/migrate/*_create_#{table_name}.rb")).first
        return unless migration && File.exist?(migration)

        content = File.read(migration)
        index_lines = uniques.map do |cols|
          cols_ruby = cols.is_a?(Array) ? "[#{cols.map { |c| ":#{c}" }.join(', ')}]" : ":#{cols}"
          "    add_index :#{table_name}, #{cols_ruby}, unique: true"
        end

        content.sub!(/^(    end\n  end\n)/) { "    end\n#{index_lines.join("\n")}\n  end\n" }
        File.write(migration, content)
        say_status "unique", "#{resource['name']}: #{uniques.inspect}", :yellow
      end

      def patch_endpoint_actions(resource)
        actions = resource["actions"]
        return unless actions&.any?

        file_name = resource["name"].underscore
        plural = resource["plural"] || file_name.pluralize
        path = File.join(destination_root, "app/endpoints/#{plural}_endpoint.rb")
        return unless File.exist?(path)

        content = File.read(path)
        return if content.include?("actions:")

        actions_ruby = actions.map do |a|
          "{name: :#{a['name']}, method: :#{a['method'].downcase}, on: :#{a['on']}}"
        end.join(", ")

        inserted = false
        %w[relations: per_page: filter: sort: permit:].each do |marker|
          if content.include?(marker) && !inserted
            content.sub!(/(#{Regexp.escape(marker)}[^\n]*\n)/) { "#{$1}    actions: [#{actions_ruby}],\n" }
            inserted = true
          end
        end

        File.write(path, content) if inserted
        say_status "actions", "#{resource['name']}: #{actions.map { |a| a['name'] }.join(', ')}", :yellow
      end

      def topological_sort(resources)
        by_name = resources.each_with_object({}) { |r, h| h[r["name"]] = r }
        visited = {}
        sorted = []

        visit = ->(name) {
          return if visited[name]
          visited[name] = true
          resource = by_name[name]
          return unless resource

          (resource["relations"] || {}).each do |_, rel|
            visit.call(rel["resource"]) if rel["kind"] == "belongs_to"
          end

          sorted << resource
        }

        resources.each { |r| visit.call(r["name"]) }
        sorted
      end
    end
  end
end
